/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;
        
import java.awt.Color;

/**
 *
 * @author Leonardo Leal
 */
public class TelaDados extends javax.swing.JFrame {

    /**
     * Creates new form TelaDados
     */
    public TelaDados() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnOrganizar = new javax.swing.JButton();
        btnEstatisticas = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        cbAmazonia = new javax.swing.JCheckBox();
        cbCaatinga = new javax.swing.JCheckBox();
        cbCerrado = new javax.swing.JCheckBox();
        cbMataAtlantica = new javax.swing.JCheckBox();
        cbPampa = new javax.swing.JCheckBox();
        cbPantanal = new javax.swing.JCheckBox();
        lbInsiraDados = new javax.swing.JLabel();
        lbBioma = new javax.swing.JLabel();
        lbEstado = new javax.swing.JLabel();
        comboxEstado = new javax.swing.JComboBox<>();
        lbArea = new javax.swing.JLabel();
        tfArea = new javax.swing.JTextField();
        lbData = new javax.swing.JLabel();
        ftfData = new javax.swing.JFormattedTextField();
        btnAdicionar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(91, 129, 112));
        jPanel1.setPreferredSize(new java.awt.Dimension(410, 20));

        btnOrganizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnOrganizar.setForeground(new java.awt.Color(255, 255, 255));
        btnOrganizar.setText("ORGANIZAR");
        btnOrganizar.setContentAreaFilled(false);
        btnOrganizar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrganizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnOrganizarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnOrganizarMouseEntered(evt);
            }
        });
        btnOrganizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrganizarActionPerformed(evt);
            }
        });

        btnEstatisticas.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnEstatisticas.setForeground(new java.awt.Color(255, 255, 255));
        btnEstatisticas.setText("ESTATISTICAS");
        btnEstatisticas.setContentAreaFilled(false);
        btnEstatisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEstatisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnEstatisticasMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnEstatisticasMouseEntered(evt);
            }
        });
        btnEstatisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstatisticasActionPerformed(evt);
            }
        });

        btnInserir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnInserir.setForeground(new java.awt.Color(255, 255, 255));
        btnInserir.setText("INSERIR");
        btnInserir.setContentAreaFilled(false);
        btnInserir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnInserir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnInserirMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnInserirMouseEntered(evt);
            }
        });
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrganizar, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstatisticas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEstatisticas)
                    .addComponent(btnOrganizar)
                    .addComponent(btnInserir))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(177, 222, 202));

        jPanel3.setPreferredSize(new java.awt.Dimension(320, 50));

        cbAmazonia.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbAmazonia.setForeground(new java.awt.Color(91, 129, 112));
        cbAmazonia.setText("Amazônia");

        cbCaatinga.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbCaatinga.setForeground(new java.awt.Color(91, 129, 112));
        cbCaatinga.setText("Caatinga");

        cbCerrado.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbCerrado.setForeground(new java.awt.Color(91, 129, 112));
        cbCerrado.setText("Cerrado");

        cbMataAtlantica.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbMataAtlantica.setForeground(new java.awt.Color(91, 129, 112));
        cbMataAtlantica.setText("Mata Atlantica");

        cbPampa.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbPampa.setForeground(new java.awt.Color(91, 129, 112));
        cbPampa.setText("Pampa");

        cbPantanal.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        cbPantanal.setForeground(new java.awt.Color(91, 129, 112));
        cbPantanal.setText("Pantanal");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbAmazonia)
                    .addComponent(cbMataAtlantica))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbPampa)
                        .addGap(18, 18, 18)
                        .addComponent(cbPantanal))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(cbCaatinga)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCerrado)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbAmazonia)
                    .addComponent(cbCaatinga)
                    .addComponent(cbCerrado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMataAtlantica)
                    .addComponent(cbPampa)
                    .addComponent(cbPantanal))
                .addContainerGap())
        );

        lbInsiraDados.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lbInsiraDados.setForeground(new java.awt.Color(102, 102, 102));
        lbInsiraDados.setText("Insira os Dados");

        lbBioma.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbBioma.setForeground(new java.awt.Color(102, 102, 102));
        lbBioma.setText("Bioma:");

        lbEstado.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbEstado.setForeground(new java.awt.Color(102, 102, 102));
        lbEstado.setText("Estado:");

        comboxEstado.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        comboxEstado.setForeground(new java.awt.Color(91, 129, 112));
        comboxEstado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre (AC)", "Alagoas (AL)", "Amapá (AP)", "Amazonas (AM)", "Bahia (BA)", "Ceará (CE)", "Distrito Federal (DF)", "Espírito Santo (ES)", "Goiás (GO)", "Maranhão (MA)", "Mato Grosso (MT)", "Mato Grosso do Sul (MS)", "Minas Gerais (MG)", "Pará (PA)", "Paraíba (PB)", "Paraná (PR)", "Pernambuco (PE)", "Piauí (PI)", "Rio de Janeiro (RJ)", "Rio Grande do Norte (RN)", "Rio Grande do Sul (RS)", "Rondônia (RO)", "Roraima (RR)", "Santa Catarina (SC)", "São Paulo (SP)", "Sergipe (SE)", "Tocantins (TO)" }));

        lbArea.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbArea.setForeground(new java.awt.Color(102, 102, 102));
        lbArea.setText("Área hm²:");

        tfArea.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        tfArea.setForeground(new java.awt.Color(91, 129, 112));
        tfArea.setText("0000");

        lbData.setFont(new java.awt.Font("Arial", 1, 15)); // NOI18N
        lbData.setForeground(new java.awt.Color(102, 102, 102));
        lbData.setText("Data:");

        ftfData.setForeground(new java.awt.Color(91, 129, 112));
        try {
            ftfData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftfData.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        btnAdicionar.setBackground(new java.awt.Color(91, 129, 112));
        btnAdicionar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        btnAdicionar.setText("ADICIONAR");
        btnAdicionar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdicionar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnAdicionarMouseEntered(evt);
            }
        });
        btnAdicionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdicionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbArea)
                            .addComponent(tfArea, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(lbData)
                                .addGap(82, 82, 82))
                            .addComponent(ftfData, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 346, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbEstado)
                            .addComponent(lbBioma)
                            .addComponent(comboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 3, Short.MAX_VALUE)))
                .addGap(24, 24, 24))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(lbInsiraDados)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(lbInsiraDados)
                .addGap(28, 28, 28)
                .addComponent(lbBioma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbEstado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboxEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbArea)
                    .addComponent(lbData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfArea, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftfData, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addComponent(btnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 32, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnInserirMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirMouseExited
        btnInserir.setBackground(new Color(235, 235, 235));
        btnInserir.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnInserirMouseExited

    private void btnInserirMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInserirMouseEntered
        btnInserir.setBackground(new Color(235, 235, 235));
        btnInserir.setForeground(new Color(217, 81, 51));
    }//GEN-LAST:event_btnInserirMouseEntered

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
       
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnOrganizarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrganizarMouseExited
        btnOrganizar.setBackground(new Color(235, 235, 235));
        btnOrganizar.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnOrganizarMouseExited

    private void btnOrganizarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnOrganizarMouseEntered
        btnOrganizar.setBackground(new Color(235, 235, 235));
        btnOrganizar.setForeground(new Color(217, 81, 51));
    }//GEN-LAST:event_btnOrganizarMouseEntered

    private void btnEstatisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticasMouseExited
        btnEstatisticas.setBackground(new Color(235, 235, 235));
        btnEstatisticas.setForeground(new Color(255,255,255));
    }//GEN-LAST:event_btnEstatisticasMouseExited

    private void btnEstatisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEstatisticasMouseEntered
        btnEstatisticas.setBackground(new Color(235, 235, 235));
        btnEstatisticas.setForeground(new Color(217, 81, 51));
    }//GEN-LAST:event_btnEstatisticasMouseEntered

    private void btnEstatisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstatisticasActionPerformed
        new TelaEstatisticas().setVisible(true);
    }//GEN-LAST:event_btnEstatisticasActionPerformed

    private void btnAdicionarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseExited
        btnAdicionar.setBackground(new Color(91,129,112));
        btnAdicionar.setForeground(new Color(255, 255, 255));
    }//GEN-LAST:event_btnAdicionarMouseExited

    private void btnAdicionarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAdicionarMouseEntered
        btnAdicionar.setBackground(new Color(235, 235, 235));
        btnAdicionar.setForeground(new Color(217, 81, 51));
    }//GEN-LAST:event_btnAdicionarMouseEntered

    private void btnAdicionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAdicionarActionPerformed

    private void btnOrganizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrganizarActionPerformed
        new TelaOrganizar().setVisible(true);
    }//GEN-LAST:event_btnOrganizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaDados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaDados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionar;
    private javax.swing.JButton btnEstatisticas;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnOrganizar;
    private javax.swing.JCheckBox cbAmazonia;
    private javax.swing.JCheckBox cbCaatinga;
    private javax.swing.JCheckBox cbCerrado;
    private javax.swing.JCheckBox cbMataAtlantica;
    private javax.swing.JCheckBox cbPampa;
    private javax.swing.JCheckBox cbPantanal;
    private javax.swing.JComboBox<String> comboxEstado;
    private javax.swing.JFormattedTextField ftfData;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbArea;
    private javax.swing.JLabel lbBioma;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbEstado;
    private javax.swing.JLabel lbInsiraDados;
    private javax.swing.JTextField tfArea;
    // End of variables declaration//GEN-END:variables
}
